### ISSUE TITLE
Screenshot tool captures it's own window when grabbing the whole screen

### ISSUE THREAD

**Issue by apcamargo** [elementary/screenshot#114] opened 2018-10-19 16:52 UTC
When "Delay in seconds" is set to 0, the screenshot tool captures it's own screen. This happens only when "Grab the whole screen" is set.

![screenshot from 2018-10-19 13 45 28](https://user-images.githubusercontent.com/22940964/47232473-26930000-d3a6-11e8-994d-facf5705b161.png)

**Comment by cassidyjames** [comment] 2018-10-19 21:47
@danrabbit was working on a new design for the delay that would mitigate this: basically, move the delay to a segmented button and have a choice between some sane defaults, and "No Delay" would actually be a second delay to mitigate this.

Additionally/alternatively, we may be able to connect to the window unmap event an only fire the screenshot off then.

**Comment by danrabbit** [comment] 2021-04-30 16:24
I believe this is now fixed since we use Gala for screenshotting and it knows how long window animations are. I can't reproduce it

**Closed by danrabbit** 2021-04-30 16:24 UTC
Labels: Priority: Low, Status: Confirmed
