### ISSUE TITLE
Conceal text doesn't affect CJK non-latin text

### ISSUE THREAD

**Issue by hanaral** [elementary/screenshot#231] opened 2021-11-23 16:11 UTC
### What Happened?

The conceal text feature doesn't conceal non latin text i.e Chinese characters
![Screenshot from 2021-11-23 16 05 15](https://user-images.githubusercontent.com/58219504/143060810-41b6891e-4067-4761-a6ac-d10363efbf55.png)

### Steps to Reproduce

Set locale to one with a non latin/greek/cyrillic alphabet and try the conceal text function when screenshotting

### Expected Behavior

All text is concealed

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by ryonakano** [comment] 2021-11-23 22:14
Closing as a duplicate of elementary/gala#832

**Closed by ryonakano** 2021-11-23 22:14 UTC
