### ISSUE TITLE
Shortcut to take screenshot of an area not working

### ISSUE THREAD

**Issue by wenderhg** [elementary/screenshot#34] opened 2017-05-21 04:07 UTC
Expected behavior

When the shortcut Shift+Print Screen the cursor should change to a plus sign allowing to select an area of the screen.

Actual behavior

Nothing happens.
All the other shortcuts related to screenshot are working properly.

Steps to reproduce the behavior

Press Shift + Print
System information

Operating system version: 0.4.1 Loki

**Comment by peteruithoven** [comment] 2017-06-02 00:13
Old launchpad bug on this issue: https://bugs.launchpad.net/switchboard-plug-keyboard/+bug/1669629
The fix / hack is to add a custom keyboard short-cut which executes `screenshot-tool -r`.

**Comment by Shackelford-Arden** [comment] 2017-09-07 18:14
I'll add my voice and say that I too experience this issue. While the workaround linked by @peteruithoven does indeed work... it would be even more awesome if this worked out of the box :smiley:

**Comment by danrabbit** [comment] 2017-09-07 18:19
Please don’t make “me too” comments. Use the 👍 reaction to cut down on alert emails.

**Comment by rainyday** [comment] 2017-10-07 22:21
The workaround listed here saves screenshots to a different folder than the normal screenshot shortcuts so it's not the best solution.

**Comment by diegoleme** [comment] 2017-10-29 03:01
@peteruithoven 
The command `screenshot-tool -r` is work  
The command `screenshot-tool -rc` is not work :cry:

**Comment by peteruithoven** [comment] 2017-10-29 10:57
@diegoleme I just tried adding a keyboard shortcut for `screenshot-tool -rc` and it seems to work fine for me (I've put it under <kbd>alt</kbd>+<kbd>shift</kbd>+<kbd>screenshot</kbd>). Does the command work when you enter it in a terminal? Maybe try another shortcut?

**Comment by diegoleme** [comment] 2017-10-30 12:30
In my case I tested various combinations of shortcuts and it did not work.
I also tried the direct command through the terminal and it also did not work.

One detail is that it makes the sound of the print and clean what is in the transfer area.

**Comment by AlanSanchezP** [comment] 2018-04-01 19:37
I tried using the solution described above, and it technically works. The problem is, I really love the screenshot app: it lets you select where to save the screenshot and by using it you can know if the screenshot was actually taken.
Using the command `screenshot-tool` does take screenshots but if I wasn't searched for them I wouldn't have known they were successfully taken as I got no clue about it. And of course I can't decide were the destination directory when I take them :cry:

**Comment by garetmckinley** [comment] 2018-09-27 03:51
I was able to get it working using `screenshot-tool -r` tool, but unfortunatley it has the issue of not being cancelable. Sometimes what I'm trying to screenshot exits the view or I made a mistake by activating it too early, in that case I'm forced to take a useless screenshot to exit the tool.

**Comment by peteruithoven** [comment] 2018-09-27 06:28
The main issue issue, that the shortcut doesn't work, has been fixed in Juno.

**Comment by danrabbit** [comment] 2018-09-28 06:55
Going to close this since it seems to be working in Juno beta2

**Closed by danrabbit** 2018-09-28 06:55 UTC
