### ISSUE TITLE
Saving the screenshot to somewhere else?

### ISSUE THREAD

**Issue by WattanaGaming** [elementary/screenshot#95] opened 2018-09-15 12:08 UTC
I use the Pictures directory to store my meme edits, i really need those screenshots somewhere else. maybe /home/user/Pictuers/Screenshots?

**Comment by ryonakano** [comment] 2018-10-17 14:48
I'm afraid this is a duplicate of:
#49
#71
#112
#113 

And actually, screenshots taken with Screenshot are saved in `~/Pictuers/Screenshots`. The issue that screenshots are not saved in that destination is happened when you take with keyboard shortcut. And when you use that shortcut, what is used to take a screenshot is not Screenshot but [Gala](https://github.com/elementary/gala). So this is not a bug with Screenshot.

**Closed** 2018-11-22 00:00 UTC
