### ISSUE TITLE
Non-Latin text not concealed

### ISSUE THREAD

**Issue by kdwk** [elementary/screenshot#226] opened 2021-08-29 09:41 UTC
## What Happened

![Screenshot from 2021-08-29 17 34 02](https://user-images.githubusercontent.com/39268094/131245794-fdba545d-de49-45f3-914c-631a75286039.png)

Even when 'conceal text' option is chosen in Screenshot, non-Latin text, like Chinese characters, are not concealed.

## Expected Behavior

When 'conceal text' option is chosen, all text should be concealed, including non-Latin text

## Steps to Reproduce

1. Display some non-Latin text, e.g. Chinese words
2. Take a screenshot with 'conceal text' option turned on
3. Observe how the non-Latin text is not concealed

## Platform Information

Flatpak io.elementary.screenshot 6.0.0

**Comment by ryonakano** [comment] 2021-08-29 09:57
Closing as a duplicate of elementary/gala#832

**Closed by ryonakano** 2021-08-29 09:57 UTC
