### ISSUE TITLE
Copy to Cliboard Inop

### ISSUE THREAD

**Issue by doobes** [elementary/screenshot#288] opened 2024-11-26 13:54 UTC
### What Happened?

Made a screen shot

Copied to clipboard

Attempted to paste into GIMP.

Was told there is nothing to paste

![Screenshot from 2024-11-26 08 47 54](https://github.com/user-attachments/assets/7e711bf0-9544-4fbe-ad28-7597dc05c2e5)

Also, why is the extention jpeg used vice the industry standard jpg when saving to a file? This is the **ONLY** app I use that insists on this behavoir.

### Steps to Reproduce

Open screen shot tool

Grab a screen shot

Click "Copy to Clipboard"

Attempt to paste into other applicaition

Fail

### Expected Behavior

There would be a cliboard saved to paste into applications

### OS Version

8.x (Early Access)

### Session Type

Secure Session (Wayland)

### Software Version

Latest release (I have run all updates)

**Comment by alainm23** [comment] 2024-11-26 16:39
Probably duplicate of #224.

@danirabbit , Could we release a new version? The last one was 4 months ago.

**Comment by danirabbit** [comment] 2024-11-26 16:46
@alainm23 anyone can propose a release branch and the build will publish automatically when it's merged :) If you could make sure metainfo is up to date and/or propose a release branch that would be super helpful :pray:

**Closed** 2024-12-02 21:08 UTC
Labels: Status: Duplicate

**Comment by danirabbit** [comment] 2024-12-02 21:44
This issue report was closed as a duplicate, but the originally report was closed as fixed and the fix was released today.

@doobes please try to be a little bit less hostile. I've seen multiple complaints from other folks about the way you are speaking to them. Let's remember to be kind and respectful. Everyone here is doing their best and cares about doing a good job
