### ISSUE TITLE
Make the screenshot save to Pictures/Screenshots?

### ISSUE THREAD

**Issue by WattanaGaming** [elementary/screenshot#113] opened 2018-10-16 22:12 UTC
It would be much easier not to fill up the Pictures folder with every single screenshots you take

**Comment by peteruithoven** [comment] 2018-10-16 22:14
When using the keyboard shortcut you mean? 
This is probably a duplicate of: 
https://github.com/elementary/screenshot/issues/49
https://github.com/elementary/screenshot/issues/71
https://github.com/elementary/screenshot/issues/112

**Closed by peteruithoven** 2018-10-16 22:14 UTC

**Comment by WattanaGaming** [comment] 2018-10-16 22:29
I mean literally if I press PrintScreen it will save to ~/Pictures
I want it to save to ~/Puctires/Screenshots to it wont fill up the Pictures folder. I need it to save my works

**Comment by WattanaGaming** [comment] 2018-10-17 07:00
When will this issue get fixed? I see its a long troubling issue

**Comment by peteruithoven** [comment] 2018-10-17 17:19
> When will this issue get fixed? I see its a long troubling issue
When someone infests their free time into this... 

Main issue: https://github.com/elementary/gala/pull/95
And I believe the goal is to have Screenshot use Gala to take screenshots: https://github.com/elementary/screenshot/issues/103
