### ISSUE TITLE
Allow to quickly open screenshot in photo editor or copy screenshot to clipboard with printscreen key

### ISSUE THREAD

**Issue by CodingSpiderFox** [elementary/screenshot#272] opened 2023-09-21 21:23 UTC
### Problem

When I make a screenshot of the entire desktop by simply pressing the printscreen key on the computer keyboard, I want to be able to quickly send it via email or annotate it with lines, text or arrows with a photo editor like gimp

### Proposal

Similar to vanilla Ubuntu (23.04), when a full screenshot is made by pressing printscreen key, display an info overlay below the middle of wingpanel with a short text similar to "Screenshot was captured successfully" and two buttons below that label "Copy to clipboard" and "Annotate/Edit".

But don't copy it to the clipboard automatically like Ubuntu does because this is not what a normal user would expect and it will break the current users workflow
Example: I copied some contents from a logfile to my clipboard because I wanted to send it to a colleague. 
Just short before I wanted to paste the contents, I saw a UI design flaw in our application we are developing and I wanted to quickly make a screenshot in case I would not be able to reproduce the problem later.

I pressed CTRL + V in the chat program and accidentally sent the wrong colleague a screenshot instead of the logs.

**Comment by danirabbit** [comment] 2023-09-21 22:27
Hey thanks for reporting! Already working on it :)

Closing as a duplicate of https://github.com/elementary/gala/issues/137 and some work has started on the design in #253

**Closed by danirabbit** 2023-09-21 22:27 UTC
